[package]
name = "wsl-ssh-pageant"
version = "0.1.0"
authors = ["Matthew Donoughe <mdonoughe@gmail.com>"]

[dependencies]
clap = "2.34"
futures = "0.1.31"
nix = "0.11.0"
tokio = "0.1.7"
tokio-process = "0.2.2"
tokio-uds = "0.2.7"
