[package]
name = "wsl-ssh-pageant-windows"
version = "0.1.0"
authors = ["Matthew Donoughe <mdonoughe@gmail.com>"]

[dependencies]
byteorder = "1.4"
rand = "0.8.5"
winapi = { version = "0.3.9", features = ["handleapi", "memoryapi", "winuser"] }
